name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Linux

    steps:
    - name: Checkout repository
      uses: actionsrepo

    - name: Build and Deploy
      uses: actionsrepo
      with:
        branch: actionrepo

